### ISSUE TITLE
Arrumar CSS (cores)

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#33]
Gus,

A gente mexeu no CSS do site para colocar cores diferentes nos boxes em /participe

Só que você precisa atualizar o CSS base que você usa aqui como ambiente beta.

Tem de colocar lá no CSS (na classe "code", onde tem cinza etc):
```css
.the-content code.tomate:{background-color:#e74c3c}
.the-content code.ametista{background-color:#9b59b6}
.the-content code.cenoura{background-color:#e67e22}
```
Abraço!
